"""creating tables

Revision ID: 3758f14ab2cc
Revises: 
Create Date: 2019-06-26 09:31:54.349655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3758f14ab2cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('publisherId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisherId'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorbook',
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['author.id'], ),
    sa.ForeignKeyConstraint(['bookId'], ['book.id'], ),
    sa.PrimaryKeyConstraint('authorId', 'bookId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorbook')
    op.drop_table('book')
    op.drop_table('publisher')
    op.drop_table('author')
    # ### end Alembic commands ###
